parameters:
- name: imageName
  displayName: "Name the image to be created, example: lzocateli/devops-agent-pool-linux-x64"
  type: string
  default: ""
- name: imageVersion
  displayName: "Tag version for the image, example: 1.0.0"
  type: string
  default: ""
- name: DockerFilePath
  displayName: "Dockerfile path, example: base-image/agent"
  type: string
  default: ""
- name: imageArguments
  displayName: "Image arguments, example: --build-arg Env_HttpProxy=proxy.mydomain.com:80"
  type: string
  default: " "
- name: proxyBypassConfig
  displayName: "Array bypass example: yourdns\\.com, github\\.com"
  type: string
  default: " "
- name: agentTargetArch
  displayName: "Target arch agent"
  type: string
  default: linux-x64
  values:
    - linux-x64
    - linux-arm64
    - linux-arm
    - rhel.6-x64


trigger: none


resources:
  pipelines:
  - pipeline: CI-Github-devops-agent-linux-base-image
    source: CI-Github-devops-agent-linux
    #project: FabrikamProject
    trigger:
      branches:
        include:
        - main
  repositories:
  - repository: templates
    type: git
    name: SharedKernel/pipelines-store
    endpoint: SharedProjects-Repos
  


variables:
- template: variables/global.yml@templates


stages: 

- template: pipeline-templates/create-image-steps.yml@templates
  parameters:
    imageName: ${{ parameters.imageName }}
    imageVersion: ${{ parameters.imageVersion }}
    DockerFilePath: ${{ parameters.DockerFilePath }}
    imageArguments: ${{ parameters.imageArguments }}
    proxyBypassConfig: ${{ parameters.proxyBypassConfig }}
    executeInstallAgent: true
    agentTargetArch: ${{ parameters.agentTargetArch }}
