parameters:
- name: imageName
  displayName: "Name the image to be created, example: lzocateli/az-powershell-linux"
  type: string
  default: ""
- name: imageVersion
  displayName: "Tag version for the image, example: 11.3.1-ubuntu-22.04"
  type: string
  default: ""
- name: DockerFilePath
  displayName: "Dockerfile path, example: devops-agent-pool-linux/base-image/linux"
  type: string
  default: ""
- name: imageArguments
  displayName: "Image arguments, example: --build-arg Env_HttpProxy=proxy.mydomain.com:80"
  type: string
  default: "--build-arg Env_HttpProxy="
- name: proxyBypassConfig
  displayName: "Array bypass example: yourdns\\.com, github\\.com"
  type: string
  default: "  yourdns\\.com"


# Pipeline deve ser diparado manualmente pelo DevOps
# informando os dados para criação da imagem
# https://dev.azure.com/nuuvers/Nuuvify/_build

trigger: none

pr: none


resources:
  repositories:
  - repository: templates
    type: git
    name: SharedKernel/pipelines-store
    endpoint: SharedProjects-Repos
  

variables:
- template: variables/global.yml@templates


stages: 

- template: pipeline-templates/create-image-steps.yml@templates
  parameters:
    imageName: ${{ parameters.imageName }}
    imageVersion: ${{ parameters.imageVersion }}
    DockerFilePath: ${{ parameters.DockerFilePath }}
    imageArguments: ${{ parameters.imageArguments }}
    proxyBypassConfig: ${{ parameters.proxyBypassConfig }}
    executeInstallAgent: false
