parameters:
- name: imageName
  displayName: "Name the image to be created, example: lzocateli/az-powershell-7.2-ubuntu-20.04"
  type: string
  default: ""
- name: imageVersion
  displayName: "Tag version for the image, example: 1.0.0"
  type: string
  default: ""
- name: DockerFilePath
  displayName: "Dockerfile path, example: base-image/linux"
  type: string
  default: ""
- name: imageArguments
  displayName: "Image arguments, example: --build-arg Env_HttpProxy=proxy.mydomain.com:80"
  type: string
  default: " "
- name: proxyBypassConfig
  displayName: "Array bypass example: yourdns\\.com, github\\.com"
  type: string
  default: " "



trigger:
  branches:
    include:
      - main

pr: none


resources:
  repositories:
  - repository: templates
    type: git
    name: SharedKernel/pipelines-store
    endpoint: SharedProjects-Repos
  

stages: 

- template: pipeline-templates/create-image-steps.yml@templates
  parameters:
    imageName: ${{ parameters.imageName }}
    imageVersion: ${{ parameters.imageVersion }}
    DockerFilePath: ${{ parameters.DockerFilePath }}
    imageArguments: ${{ parameters.imageArguments }}
    proxyBypassConfig: ${{ parameters.proxyBypassConfig }}
    executeInstallAgent: false
